name: Python CI - Tests, Lint, Coverage, Docs

on:
  push:
    branches: [CIworkflow]
  pull_request:
    branches: [CIworkflow]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .  # from pyproject.toml
          pip install pytest pytest-cov ruff mkdocs

      - name: Lint with Ruff
        run: |
          ruff check 

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=term-missing

      - name: Build documentation (MkDocs)
        run: |
          mkdocs build --strict