name: Tests for Zalmoxis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Zalmoxis-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.9"

      - name: Set ZALMOXIS_ROOT environment variable
        run: echo "ZALMOXIS_ROOT=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .  # from pyproject.toml
          pip install pytest pytest-cov pytest-xdist ruff mkdocs mkdocs-material markdown-include mkdocstrings[python] pymdown-extensions

      - name: Download required input/output files
        run: |
          bash src/get_zalmoxis.sh

      - name: Lint with Ruff
        run: |
          ruff check 

      - name: Run tests with coverage
        run: |
          pytest -n auto --cov=src --cov-report=term-missing

      - name: Build documentation (MkDocs)
        run: |
          mkdocs build --strict